CREATE TABLE IF NOT EXISTS announcements (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  type TEXT NOT NULL DEFAULT 'info',
  priority TEXT NOT NULL DEFAULT 'normal',
  status TEXT NOT NULL DEFAULT 'draft',
  active INTEGER NOT NULL DEFAULT 1,
  audience TEXT NOT NULL DEFAULT 'customers',
  selected_emails TEXT,
  placements TEXT NOT NULL,
  starts_at TEXT,
  ends_at TEXT,
  image_url TEXT,
  icon TEXT,
  accent_color TEXT,
  button_text TEXT,
  button_url TEXT,
  button_target TEXT DEFAULT '_self',
  dismissible INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 100,
  views INTEGER NOT NULL DEFAULT 0,
  read_by TEXT,
  dismissed_by TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  published_at TEXT
);
